# =============================================================================
# Development Overrides — compose.override.yml
# =============================================================================
# This file is automatically loaded by `docker compose up` when present.
# It adds development-friendly configuration on top of compose.yml:
#   - Bind-mounted source code for live editing
#   - Debug port exposed
#   - Flask debug mode enabled
#
# For production, use: docker compose -f compose.yml up
# (explicitly excluding the override file)
# =============================================================================

services:
  api:
    # Mount source code for live editing (changes reflect without rebuild)
    volumes:
      - ./lab_02_app.py:/app/app.py:ro

    # Expose debug port
    ports:
      - "8080:8080"

    # Enable Flask debug mode
    environment:
      - FLASK_DEBUG=1

  db:
    # Expose database port for direct access during development
    ports:
      - "5432:5432"
